### ISSUE TITLE
Procedure for obtaining conglomerate sets

### ISSUE THREAD

**Issue by miheerdew** [jpalowitch/cbce#2]
https://github.com/jpalowitch/cbce/blob/005c4cd4584166aa9329fbd9ea5536f130869fa5/R/cbce.R#L273

Should the 0.5 be changed to 1-OL_thresh?

**Comment by jpalowitch** [comment]
Fairly sure it's just 0.5 --> OL_thresh. Feel free to make the change. I won't be able to until later.

**Comment by miheerdew** [comment]
The default value of OL_thresh is .9, and we are looking at jaccard distance (not similarity) here. So we want to break if some distance is greater that .1 rather than .9. Hence I believe it should be 1-OL_thresh

**Comment by jpalowitch** [comment]
I'll trust you on this, but can you point me to where jaccard is defined()?

**Comment by jpalowitch** [comment]
Haha, sorry. *jaccard(), and *defined.

**Comment by miheerdew** [comment]
The Jaccard distance is defined [here](https://github.com/jpalowitch/cbce/blob/005c4cd4584166aa9329fbd9ea5536f130869fa5/R/utils.R).

**Comment by miheerdew** [comment]
And then the jaccards between two modules (A_1,B_1) and (A_2,B_2) [is defined as](https://github.com/jpalowitch/cbce/blob/005c4cd4584166aa9329fbd9ea5536f130869fa5/R/cbce.R#L145) `jaccard(A_1 U B_1, A_2 U B_2)`. This might also be a good time to point out that this is almost determined by the SNP sets (which are usually large). An alternative is to take the mean of the Gene jaccards with the SNP jaccards.

**Comment by jpalowitch** [comment]
Agreed, 1 - OL_thres. Good point re SNP sets. However, I prefer to keep it consistent with the fact that we're treating {Genes} U {SNPs} as the "module" unit which is being updated. If we go back to alternating updates between Genes & SNPs, the averaging would make more sense.
